(components) feature: upgraded the Modal to @wethegit/react-modal v3
wethegit/component-library pull request #350
Opened 2024-09-24 23:49 UTC by pravton

## Description

Upgraded the Modal component to use the latest version (v3) of @wethegit/react-modal which addresses the issue #318

Task: https://wethecollective.teamwork.com/app/tasks/22769488

2024-09-25 17:08 UTC, andrewrubin requested changes
Thanks for the updates @pravton! Couple notes from me, but we also need to clean up the docs:

This sentence is incorrect (there's no `trigger` prop on the Modal):
> _The <Modal> component takes a trigger prop that is a function which receives a toggle function as its only argument and should return the element that will trigger the modal._

Can we just re-word some of these docs to explain the usage better, i.e. how the `useModal` hook returns the props required for the Modal itself (`toggle` and `triggerRef`), as well as the `isOpen` state.

2024-09-25 21:57 UTC, pravton commented on packages/wethegit-components/src/components/modal/modal.tsx
I agree and I like the idea of being explicit in accepting the renderTo prop. So I updated this with the renderRo Prop.

2024-09-25 21:57 UTC, pravton commented on packages/wethegit-components/src/components/modal/modal.stories.tsx
Thanks, great catch! I have also removed this!

2024-09-25 22:05 UTC, pravton commented
@andrewrubin I have also updated the readme and the example and ready for you when you have a moment!

2024-09-25 22:20 UTC, andrewrubin commented
It's looking good to me @pravton. I think we're ready for a changeset on this one 🎉

2024-10-03 18:00 UTC, andrewrubin approved these changes

2024-10-03 18:00 UTC, merged